

barrel_shifter_tb: barrel_shifter.vhdl barrel_shifter_tb.vhdl
	ghdl -a --ieee=standard barrel_shifter.vhdl barrel_shifter_tb.vhdl && ghdl -e --ieee=standard barrel_shifter_tb && ghdl -r --ieee=standard barrel_shifter_tb --vcd=barrel_shifter.vcd



